### ISSUE TITLE
Crashed with Apple silicon M1

### ISSUE THREAD

**Issue by nguyenpham** [algerbrex/blunder#23]
I have been trying the latest version, using the binaries (both default and popcnt) that come with the release on an Apple M1. Below is the screen capture:

```
MacBook-Pro macOS % ./blunder-8.5.5-default
Finding rook and bishop magics... 
Done finding rook and bishop magics.

██████╗░██╗░░░░░██╗░░░██╗███╗░░██╗██████╗░███████╗██████╗░
██╔══██╗██║░░░░░██║░░░██║████╗░██║██╔══██╗██╔════╝██╔══██╗
██████╦╝██║░░░░░██║░░░██║██╔██╗██║██║░░██║█████╗░░██████╔╝
██╔══██╗██║░░░░░██║░░░██║██║╚████║██║░░██║██╔══╝░░██╔══██╗
██████╦╝███████╗╚██████╔╝██║░╚███║██████╔╝███████╗██║░░██║
╚═════╝░╚══════╝░╚═════╝░╚═╝░░╚══╝╚═════╝░╚══════╝╚═╝░░╚═╝
	
Author: Christian Dean
Engine: Blunder 8.5.5
Email: deanmchris@gmail.com
Hash size: 64 MB
Perft hash size: 64 MB

Commands:
- uci: Start the UCI protocol
- tt <SIZE>: Set the size of the transposition table used with perft to be <SIZE> MB
- perft <DEPTH>: Run perft up to <DEPTH>
- dperft <DEPTH>: Run divide perft up to <DEPTH>
- fen <FEN>: Load a fen string given by <FEN>
- print: Display the current board state
- eval: Display the static evaluation of the current position
- help: Display this help message
- quit: Quit the program

uci

id name Blunder 8.5.5
id author Christian Dean

option name Hash type spin default 64 min 1 max 32000
option name Clear Hash type button
option name Clear History type button
option name Clear Killers type button
option name Clear Counters type button
option name UseBook type check default false
option name BookPath type string default
option name BookMoveDelay type spin default 2 min 0 max 10

Available UCI commands:
    * uci
    * isready
    * ucinewgame
    * setoption name <NAME> value <VALUE>
    * position
	* fen <FEN>
	* startpos
    * go
	* wtime <MILLISECONDS>
	* btime <MILLISECONDS>
	* winc <MILLISECONDS>
	* binc <MILLISECONDS>
	* movestogo <INTEGER>
	* depth <INTEGER>
	* nodes <INTEGER>
	* movetime <MILLISECONDS>
	* infinite
    * stop
    * quit

uciok

isready
readyok
ucinewgame
position fen r1bqk1r1/1p1p1n2/p1n2pN1/2p1b2Q/2P1Pp2/1PN5/PB4PP/R4RK1 w q -
panic: runtime error: slice bounds out of range [:6] with capacity 4

goroutine 1 [running]:
blunder/engine.(*UCIInterface).positionCommandResponse(0xc000260000, {0xc00001c140?, 0x4b?})
	C:/Users/deanm/Desktop/blunder/engine/uci.go:73 +0x4c6
blunder/engine.(*UCIInterface).UCILoop(0xc000260000)
	C:/Users/deanm/Desktop/blunder/engine/uci.go:250 +0x539
blunder/engine.RunCommLoop()
	C:/Users/deanm/Desktop/blunder/engine/comm.go:148 +0x832
main.main()
	C:/Users/deanm/Desktop/blunder/blunder/main.go:16 +0x17

```

**Comment by nguyenpham** [comment]
Sorry, my bad. The FEN I used to test is missing last two numbers (half move clock and full move counter).
